### ISSUE TITLE
Convertion of filament within Linux WSL will only convert one ini File

### ISSUE THREAD

**Issue by Sempre** [theophile/SuperSlicer_to_Orca_scripts#11]
I have tried to convert all my Filaments within an Ubuntu 22.04.3 LTS WSL instance. The conversition was done with access to the SuperSlicer installation on Windows and with the following command:

perl superslicer_to_orca.pl --input /mnt/c/User/<Username>/AppData/Roaming/SuperSlicer/filament/*.ini --outdir ../converted/ --nozzle-size 0.4 --force-output

As Result i got:
![grafik](https://github.com/theophile/SuperSlicer_to_Orca_scripts/assets/6272314/93dcb9b9-3ed1-46b9-83be-f19a570f168e)

Its is reproducible with the usage of specific Filament names

![grafik](https://github.com/theophile/SuperSlicer_to_Orca_scripts/assets/6272314/2ac5142b-00f9-4dfd-85ba-ecaefa272cb2)

An as a proof there is the list of Filaments availabile

![grafik](https://github.com/theophile/SuperSlicer_to_Orca_scripts/assets/6272314/526da235-5a8b-40d3-aee4-5df2b8bcb1d3)

I tried the same directly within windows and with Strawberry Perl which leads to success

![grafik](https://github.com/theophile/SuperSlicer_to_Orca_scripts/assets/6272314/6a9f2505-dd61-4af9-9605-d9633f1d70f1)

Regards

**Comment by theophile** [comment]
Interesting. It looks like the wildcard expansion isn't working right on WSL/Linux. I'll spin up my Ubuntu installation and do some testing. In the meantime, can you let me know what happens if you use the following parameters for the `--input` command?
* `"/mnt/c/User//AppData/Roaming/SuperSlicer/filament/*.ini"` (enclosed in quotation marks)
* `/mnt/c/User//AppData/Roaming/SuperSlicer/filament/` (just the directory path)

**Comment by theophile** [comment]
> Tested both and seems to be working. Just for your information, as i started the WSL Linux a few minutes ago there was an update to wsl which i did. It could be a coincidence but i thought i mention it.

Thanks @Sempre. I think I've identified and fixed the problem. Please do a `git pull` and let me know if your original command (with wildcard and no quotes) works as expected now.

**Comment by Sempre** [comment]
@theophile 

> Thanks @Sempre. I think I've identified and fixed the problem. Please do a git pull and let me know if your original command (with wildcard and no quotes) works as expected now.

Did a test and it seems to be working now aas expedcted. Thank you for the fast response and fix

**Comment by theophile** [comment]
Great! Thanks for the feedback!
