### ISSUE TITLE
Not working on Ubunbtu 23.04

### ISSUE THREAD

**Issue by mechano** [theophile/SuperSlicer_to_Orca_scripts#12]
Only errors on Ubuntu 23.04, Perl v5.36.0

mechano@desktop:~/Lavoro/Stampa 3D$ perl superslicer_to_orca.pl 
Bareword found where operator expected at superslicer_to_orca.pl line 8, near ""en" data"
	(Missing operator before data?)
Bareword found where operator expected at superslicer_to_orca.pl line 8, near ""auto" data"
	(Missing operator before data?)
Bareword found where operator expected at superslicer_to_orca.pl line 8, near ""light" data"
	(Missing operator before data?)
Bareword found where operator expected at superslicer_to_orca.pl line 8, near ""dark"  data"
	(Missing operator before data?)
Bareword found where operator expected at superslicer_to_orca.pl line 8, near ""system" data"
	(Missing operator before data?)
Bareword found where operator expected at superslicer_to_orca.pl line 33, near "" src="https"
	(Missing operator before https?)
Bareword found where operator expected at superslicer_to_orca.pl line 33, near "49784d71d63b"
	(Missing operator before d71d63b?)
String found where operator expected at superslicer_to_orca.pl line 33, near "<script crossorigin=""
	(Missing semicolon on previous line?)
Bareword found where operator expected at superslicer_to_orca.pl line 34, near "<script crossorigin="anonymous"
  (Might be a runaway multi-line "" string starting on line 33)
	(Missing operator before anonymous?)
String found where operator expected at superslicer_to_orca.pl line 34, near "anonymous" defer=""
Bareword found where operator expected at superslicer_to_orca.pl line 34, near "" defer="defer"
	(Missing operator before defer?)
String found where operator expected at superslicer_to_orca.pl line 34, near "defer" type=""
Bareword found where operator expected at superslicer_to_orca.pl line 34, near "" type="application"
	(Missing operator before application?)
String found where operator expected at superslicer_to_orca.pl line 34, near "javascript" src=""
Bareword found where operator expected at superslicer_to_orca.pl line 34, near "" src="https"
	(Missing operator before https?)
Can't modify numeric lt (<) in scalar assignment at superslicer_to_orca.pl line 8, near ""en" data"
syntax error at superslicer_to_orca.pl line 8, near ""en" data"
Unknown regexp modifier "/j" at superslicer_to_orca.pl line 33, at end of line
Unknown regexp modifier "/v" at superslicer_to_orca.pl line 33, at end of line
Unknown regexp modifier "/r" at superslicer_to_orca.pl line 33, at end of line
Unknown regexp modifier "/t" at superslicer_to_orca.pl line 33, at end of line
Unknown regexp modifier "/t" at superslicer_to_orca.pl line 33, at end of line
Unknown regexp modifier "/h" at superslicer_to_orca.pl line 33, at end of line
Unknown regexp modifier "/b" at superslicer_to_orca.pl line 33, at end of line
Unknown regexp modifier "/t" at superslicer_to_orca.pl line 34, at end of line
superslicer_to_orca.pl has too many errors.

**Comment by theophile** [comment]
You're not actually running the script. If you want to download the .pl file directly instead of cloning the git repo, you need to download the "raw" version of the file: 
`https://raw.githubusercontent.com/theophile/SuperSlicer_to_Orca_scripts/main/superslicer_to_orca.pl`
