### ISSUE TITLE
Ironing and Elephant foot

### ISSUE THREAD

**Issue by B0IIE** [theophile/SuperSlicer_to_Orca_scripts#19]
I used your script to convert my settings from PS 2.6.1 to OS 1.7.0 and noticed that after importing in all my profiles Ironing was turned on even though it was disabled in PS and that Elephant foot compensatation was set to 0 even though I had it set to 0,2 mm in PS.

**Comment by theophile** [comment]
Thanks for this. Can you post a source profile where you experienced this issue?

**Comment by B0IIE** [comment]
Here´s an example.
[0.20mm NORMAL Ender3_3_3_3.zip](https://github.com/theophile/SuperSlicer_to_Orca_scripts/files/12910071/0.20mm.NORMAL.Ender3_3_3_3.zip)

**Comment by Creo2005** [comment]
> Thanks for this. Can you post a source profile where you experienced this issue?


When I imported from SS, it was the same. Ironing was turned on. In ss in off.

**Comment by theophile** [comment]
I've pushed a commit that should address the ironing problem. Let me know if not. I'll take a look at the elephant foot compensation next.

**Comment by theophile** [comment]
Elephant foot compensation should be fixed now too. I had failed to notice that PrusaSlicer and SuperSlicer have different names for the same parameter.
