### ISSUE TITLE
How TF do you use this?

### ISSUE THREAD

**Issue by TheVoronModder** [theophile/SuperSlicer_to_Orca_scripts#25]
WTF is Perl?

And how does someone who does literally NO coding make this work?

Thank you.

Please have patience with me.

**Comment by theophile** [comment]
There are installation and usage instructions here: https://github.com/theophile/SuperSlicer_to_Orca_scripts#installation

Perl is an interpreted programming language, which means that a program's "source code" doesn't have to be compiled into an executable binary. Instead, it can be executed directly by feeding it into a Perl interpreter. The first thing you need to do is install a Perl interpreter. If you're using Windows, the installation instructions contain a link where you can download a Windows Perl interpreter.

Once that's installed, just follow the rest of the instructions. In a nutshell, you will need to use the command line to call your Perl interpreter and pass this script to it as an argument.

**Comment by TheVoronModder** [comment]
So I’m not understanding how to get stawberry Perl opened at all. I downloaded and installed the software however I don’t know what or where a Perl console is? Sent from my iPhoneOn Feb 8, 2024, at 6:01 PM, theophile ***@***.***> wrote:﻿
There are installation and usage instructions here: https://github.com/theophile/SuperSlicer_to_Orca_scripts#installation
Perl is an interpreted programming language, which means that a program's "source code" doesn't have to be compiled into an executable binary. Instead, it can be executed directly by feeding it into a Perl interpreter. The first thing you need to do is install a Perl interpreter. If you're using Windows, the installation instructions contain a link where you can download a Windows Perl interpreter.
Once that's installed, just follow the rest of the instructions. In a nutshell, you will need to use the command line to call your Perl interpreter and pass this script to it as an argument.

**Comment by theophile** [comment]
Click the Windows icon/start menu. In the search box, type `cmd` and hit enter. That's the command prompt. If you don't understand how it works or how to navigate your system with it, you may have to Google it. In a nutshell, you'll need to change the working directory (`cd`) to wherever you downloaded this script, and then just follow the usage instructions in the repo.

**Comment by TheVoronModder** [comment]
Okay that makes sense. I have 6 hdd so I’ll have to change the directory to the correct drive. Thank you so much for your patience and understanding! Sent from my iPhoneOn Feb 10, 2024, at 1:50 PM, theophile ***@***.***> wrote:﻿
Click the Windows icon/start menu. In the search box, type cmd and hit enter. That's the command prompt. If you don't understand how it works or how to navigate your system with it, you may have to Google it. In a nutshell, you'll need to change the working directory (cd) to wherever you downloaded this script, and then just follow the usage instructions in the repo.

**Comment by TheVoronModder** [comment]
I am having errors with #3

**Clone this repository or download the script directly from GitHub.

git clone https://github.com/theophile/SuperSlicer_to_Orca_scripts.git**

**Comment by theophile** [comment]
You can just download the script directly: https://raw.githubusercontent.com/theophile/SuperSlicer_to_Orca_scripts/main/superslicer_to_orca.pl

**Comment by TheVoronModder** [comment]
I should have explained more, I am stuck with this part:

<img width="552" alt="image" src="https://github.com/theophile/SuperSlicer_to_Orca_scripts/assets/142328467/f60a6c5b-e607-42e6-a204-fe9553858b22">

**Comment by TheVoronModder** [comment]
<img width="484" alt="image" src="https://github.com/theophile/SuperSlicer_to_Orca_scripts/assets/142328467/7976a77d-9962-4bb7-b55b-1f32fb6eea67">

I figured it out! Thank you!
