### ISSUE TITLE
Argument "" isn't numeric in multiplication (*) at superslicer_to_orca.pl at line 323

### ISSUE THREAD

**Issue by Vanilla009** [theophile/SuperSlicer_to_Orca_scripts#29]
The script gives the error message `argument "" isn't numeric in multiplication (*) at superslicer_to_orca.pl line 323.` This repeats for 3 profiles, and the print files converted summary states that they were converted. However, they do not show up in orcaslicer, I'm assuming because of this error.

[SuperSlicer_config_bundle.zip](https://github.com/theophile/SuperSlicer_to_Orca_scripts/files/14551742/SuperSlicer_config_bundle.zip)

**Comment by theophile** [comment]
Thanks for catching that. I've pushed a commit that should fix this error. Please let me know if it resolves your issue.

**Comment by Vanilla009** [comment]
This seemed to fix that error. Thanks!
